# Generated by Django 3.0.2 on 2020-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gethelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('pno', models.IntegerField()),
                ('loc', models.CharField(max_length=15)),
                ('num', models.IntegerField()),
                ('address', models.CharField(max_length=205)),
                ('pin', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='help1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phno', models.IntegerField()),
                ('locality', models.CharField(max_length=15)),
                ('num_help', models.IntegerField()),
                ('supply', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='positive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pphno', models.IntegerField()),
                ('paddress', models.CharField(max_length=205)),
                ('ppin', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('temp', models.CharField(max_length=15)),
                ('symp', models.CharField(max_length=15)),
                ('asymp', models.CharField(max_length=15)),
                ('th', models.CharField(max_length=15)),
                ('health', models.CharField(max_length=15)),
                ('healthcond', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
