# Generated by Django 3.0.2 on 2020-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200410_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='asymp',
            field=models.CharField(choices=[('Moderate to SevereCough', 'moderate to severecough'), ('Feeling Breathless', 'feeling breathless'), ('Drowsiness', 'drowsiness'), ('Severe Weakness', 'severe weakness'), ('NoneOfThese', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='AdditionalSymptoms'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='health',
            field=models.CharField(choices=[('High Blood Pressure', 'highbloodpressure'), ('Diabeties', 'diabeties'), ('HeartDisease', 'heartdisease'), ('LungDisease', 'lungdisease'), ('Stroke', 'stroke'), ('ReducedImmunity', 'Reduced Immunity'), ('NoneOfThese', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='HealthIssue'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='healthcond',
            field=models.CharField(choices=[('High Blood Pressure', 'highbloodpressure'), ('Diabeties', 'diabeties'), ('HeartDisease', 'heartdisease'), ('LungDisease', 'lungdisease'), ('Stroke', 'stroke'), ('ReducedImmunity', 'Reduced Immunity'), ('NoneOfThese', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='HealthCondition'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symp',
            field=models.CharField(choices=[('DryCough', 'drycough'), ('Sneezing', 'sneezing'), ('SoreThroat', 'sorethroat'), ('Weakness', 'weakness'), ('NoneOfThese', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='Symptoms'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='temp',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FEVER', 'Fever'), ('HIGHFEVER', 'Highfever')], default='NORMAL', max_length=40, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='th',
            field=models.CharField(choices=[('Contact with infected patient', 'contact with infected patient'), ('traveled to affected places', 'traveled to affected places'), ('No contact with infected patient', 'No contact with infected patient'), ('NoneOfThese', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='TravelHistory'),
        ),
    ]
