# Generated by Django 3.0.2 on 2020-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200410_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='health',
            field=models.CharField(choices=[('High Blood Pressure', 'highbloodpressure'), ('Diabeties', 'diabeties'), ('Heart Disease', 'heartdisease'), ('Lung Disease', 'lungdisease'), ('Stroke', 'stroke'), ('Reduced Immunity', 'Reduced Immunity'), ('None Of These', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='HealthIssue'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='healthcond',
            field=models.CharField(choices=[('High Blood Pressure', 'highbloodpressure'), ('Diabeties', 'diabeties'), ('Heart Disease', 'heartdisease'), ('Lung Disease', 'lungdisease'), ('Stroke', 'stroke'), ('Reduced Immunity', 'Reduced Immunity'), ('None Of These', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='HealthCondition'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='th',
            field=models.CharField(choices=[('Contact with infected patient', 'contact with infected patient'), ('traveled to affected places', 'traveled to affected places'), ('No contact with infected patient', 'No contact with infected patient'), ('None Of These', 'noneofthese')], default='NoneOfThese', max_length=40, verbose_name='TravelHistory'),
        ),
    ]
