# Generated by Django 3.0.2 on 2020-04-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20200410_0650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help1',
            new_name='hel',
        ),
    ]
